# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WuYYipgng-_M_9_2MPrrGeYc1pyQAMJZ
"""

# IMPORT DATASET

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

"""EXPLORATORY DATA ANALYSIS"""

df = pd.read_csv ('CarPrice_data.csv')
df.head()

df.info()

df.describe()

df.describe().T

"""UNIVARIATE ANALYSIS"""

# UNIVARIATE DISTRIBUTION OF THE PRICE FEATURE
sb.histplot(df['price']);

"""- The distribution of the car feature is positively skewed.
- A greater number of cars from the data, fall within the price range of 5000usd to 20000usd.

"""

# UNIVARIATE DISTRIBUTION OF THE CAR FUEL TYPE
sb.countplot ( x = 'fueltype', data = df);

"""- Most cars from the data set run on gas than diesel."""

# UNIVARIATE DISTRIBUTION OF ENGINE TYPE
sb.countplot(x ='enginetype', data = df);

"""- It is observed that the vast majority of cars included in the dataset are equipped with ohc engines. Conversely, only a small proportion of the cars in the dataset feature dohcv engines."""

# DISTRIBUTION OF THE CARBODY
sb.countplot(x = 'carbody', data = df);

"""- Upon analyzing the dataset, it has been noted that the majority of the cars have a sedan car body type, with hatchbacks being the second most prevalent. On the other hand, the least common car body type observed in the dataset is the convertible.

BIVARIATE ANALYSIS
"""

# BIVARIATE ANALYSIS OF HORSE POWER AND PRICE (RELATIONSHIP BETWEEN HORSEPOWER AND PRICE)
sb.jointplot (x = 'horsepower', y = 'price', data = df);

"""- There is a positive correlation between horsepower and price. """

sb.scatterplot(x = 'horsepower', y = 'price', data = df);

"""- A positive correlation is observed between horsepower and the dependent variable, price, eventhough a number of outliers can be detected."""

# RELATIONSHIP BETWEEN THE CAR ENGINE AND LOCATION
sb.boxplot(x = 'enginelocation', y = 'price', data = df);

"""- It is observed that averagely, less expensive cars have their engines located in front, eventhough some outliers have been detected. 
- Cars that have engine located in the rear are averagely more expensive than those with their engines located in the front.
"""

sb.barplot(x = 'enginelocation', y = 'enginesize', data = df);

"""- It is observed that rear engine cars tend to have large engine size than front engine cars."""

sb.stripplot(x = 'enginetype', y = 'highwaympg', data = df);

"""- It can be that the OHC engine has a higher mpg."""

sb.boxplot(x='carbody', y = 'price', data = df);

"""- It is observed that averagely, hardtops and convertible tend to be more expensive.

MULTIVARIATE ANALYSIS
"""

# RELATIONSHIP BETWEEN CARBODY, PRICE AND ENGINE LOCATION
sb.boxplot(x = 'carbody', y = 'price', hue = 'enginelocation', data = df);

sb.boxplot(x = 'carbody', y = 'price', hue = 'enginetype', data = df);

var = ['symboling', 'wheelbase', 'carlength', 'carwidth','stroke', 'citympg', 'compressionratio', 'price']
sb.pairplot(df[var]);

plt.figure(figsize = (10,7))
sb.heatmap(df[var].corr(), annot = True);

g = sb.pairplot(df[var], kind ='reg', plot_kws = {'line_kws': {'color':'red'}, 'scatter_kws': {'alpha':0.4}});
g.fig.set_size_inches (12,12);
g.fig.suptitle ('Multivariate analysis');

"""- It has been observed that several key factors have a significant impact on a car's price. Notably, the length and width of the car, as well as its horsepower and wheelbase, have emerged as strong predictors of car prices."""

